<!DOCTYPE HTML>
<html>
  <head>
    <script type="text/javascript" src="/js/syntaxhighlighter/shCore.js"></script>
    <script type="text/javascript" src="/js/syntaxhighlighter/shBrushPhp.js"></script>
    <script type="text/javascript" src="/js/ckeditor/ckeditor.js"></script>
    <link rel="stylesheet" type="text/css" href="/js/syntaxhighlighter/shCore.css">
    <link rel="stylesheet" type="text/css" href="/js/syntaxhighlighter/shCoreDefault.css">
  </head>
  <body style="width: 1000px;"> 
    <?php echo $this->layout()->content; ?>
  </body>
</html>